/******************************************
 * THIS FILE HAS BEEN AUTOGENERATED USING *
 *                                        *
 *       create_test_suite_files.py       *
 ******************************************/

package dk.dbc.opensearch.common.db.tests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;


@RunWith(Suite.class)
@Suite.SuiteClasses(
    {
        ProcessqueueTest.class
    }
)
public class DBTestSuite 
{
    // Leave class empty!
}