/**
 * \file doxygen.java
 * \brief dummy file to hold the main documentation page.
 */

/**
 * \defgroup components Components
 * \brief The components of opensearch
 * \defgroup tools Tools
 * \brief The tools classes for facilitating the componentents and testing.
 * 
 * \defgroup datadock DataDock
 * \ingroup components 
 * \brief The datadock recieves incoming data and stores it in the repository.
 * \defgroup pti PTI
 * \ingroup components 
 * \brief The PTI component validates and indexes the newly arrived data.
 *
 */

/**
 * \mainpage 
 * \section Overview 
 * The Opensearch project has 3 different main responsibilities: 
 * - Receieving and storing data.\n    
 *   This is done in the DataDock component. 
 *   The first responsibility of this component is to receive data, and validate
 *   the necessary metadata needed for later indexing.\n
 *   Secondly the component must store the data in the fedora repository, 
 *   alert the pti component of the new task, and lastly return an estimate 
 *   of the time before the dataobject is effectively searchable.
 *   \see DataDock  
 * - Indexing data.\n
 *   This is done in the PTI component. 
 *   When alerted of a new dataobject to index this component retrives a copy 
 *   of the data from the repositoryand make it ready for indexing. Through
 *   Compass the data gets indexed and saved in the database and afterwards the 
 *   estimate table in the database gets updated.
 *   \see PTI  
 * - Facilitate search of indexed data.\n 
 *   Currently under construction.
 *
 * \section Components
 *
 * \subsection DataDock
 * The Datadock can roughly be split into these parts:
 * - Receive data.\n
 *   This part is somewhat hardcoded and only supports faktalink xml files. 
 *   Data is read from files in a directory given to the datadocks main method.
 *   The informationen needed for indexing which is mimetype, language, submitter 
 *   and format is also given to the main method. These arguments are validated, 
 *   and a CargoContainer with the data and metadata is constructed.
 * \see DataDockPoolAdmMain, DataDockPoolAdm, DataDockPool, CargoContainer 
 * - Store data in repository.\n
 *   When a CargoContainer is constructed the  DataDockPool spawns a DataDock thread.
 *   The Datadock thread stores the data in the repository through a FedoraHandler.
 *   \see DataDockPool, DataDock, FedoraHandler
 * - Alert the PTI Component of a new dataobject
 *   After the data is stored, a repository pointer is pushed onto the processqueue,
 *   which will be polled by the PTI component.
 *   \see DataDock, Processqueue
 * - Return an Estimate of the time before the dataobject is searchable.\n
 *   Reads an average processtime for data with this mimetype from the statisticDB 
 *   table in the database, and returns a suitable estimate for how long time remains 
 *   before the dataobject is searchable by the Lantern component to the subimtter.
 *   Currently the estimate is printed to the log
 *   \see DataDock, Estimate
 *
 * \subsection pti PTI (Proccesing, Transformation, BLABLA)
 * The PTI Component is thought as a deamon service that polls the processqueue for 
 * new repository pointers. it can be split into these parts:
 * - Polling processqueue and start prorcessing/indexing.\n
 *   The PTIPoolAdm class polls the processqueue, and when a new data entry is made 
 *   by the datadock, it starts a new PTI thread through the PTIPool.
 * - Process and transform data for indexing.\n
 *   This only works for faktalink xml at the moment. The Indexing is done with a 
 *   Compass instance, And the indexes in the faktalink instance re generated by using
 *   Compass XSEM mapping feature. Later other format can be index using XSEM or  the 
 *   mapping models provided by Compass. 
 * - Indexing and Storing of data.\n
 *   The Indexing and storing of the indexes is done through a CompassSession. It stores 
 *   the indexes in the oracle database. 
 * - Update Estimate for this mimetype.\n
 *   After the indexes are stored in the database the dataobject is searchable. The 
 *   PTI thread exits, and return the actual processtim for this dataobject. The average 
 *   processtime is calculated and the StatisticsDB table in the database is updated with 
 *   the new information. 
 *
 * \subsection Lantern
 * As of now this is only facilitated by BLABLA.
 *
 * \section Tools
 * Here follows a description of the tools used to facilitate the components.
 *
 * \subsection Fedorahandler
 * The FedoraHandler handles communication with the Fedora repository. 
 * - Storing data.\n
 *   When used to store data, which it does in the DataDock, the fedorahandler generates 
 *   Dublin Core data from the CargoContainer supplied in the submitDataStream method.  
 *   Afterwards the data and the Dublin Core is submitted to the repository.
 * - Retrieving data.\n
 *   The FedoraHandlers getDataStream method retrives the data from the repository, and 
 *   returns it wrapped in a CargoContainer.
 *
 * \subsection Processqueue
 * The Processqueue is used to register not yet indexed dataobjects. This class handles all 
 * communication to the porcessqueue table in the database.When the DataDock has stored
 * the data in the repository i pointer to the data is pusjed to the queue.
 * The PTI component polls the Processqueue and when a new dataelement is present it is popped 
 * from the queue. After the PTI has ended indexing the pop is now committed to the queue. 
 * If something goes wrong i the indexing a rollback of the pop is possible.
 *
 * \subsection Estimate
 * The Estimate class handles all communication with the statisticsDB table in the database, 
 * and is used to return an estimate of the time before the data is searchable.
 * It provides methods for retriving and updating estimates for the processing time of 
 * mimetypes.
 * 
 * \subsection xsd2xsem
 * xsd2xsem is a python script used to generate a XSEM mapping for for all xml documents 
 * validated by the given xsd file.
 *
 * \section Executables
 * 
 * At the moment there are 2 executables:
 * - DataDockPoolAdmMain\n
 *   starts The DataDock.\n
 *   example of usage:\n
 *   java -Dsubmitter="dbc" -Dfilepath="testdir/*.xml" -Dformat="faktalink" -Dmimetype="text/xml" -Dlang="" -cp `bin/run` dbc.opensearch.components.datadock.DataDockPoolAdm  
 * - PTIPoolAdmMain\n
 *   starts the PTI.\n
 *   example of usage:\n
 *   java -cp `bin/run` dbc.opensearch.components.pti.PTIPoolAdmMain
 *
 * \section Configuration
 * The configuration files are located in the 'opensearch/trunk/config' directory.
 * It contains the following files:
 * - compass.cfg.xml\n
     The compass configuration.
 * - config.xml\n
     Configurationfile currently containg configuration for the database access for the 
     Fedorahandler, Porcessqueue and Estimate. 
 * - log4j.xml\n
     Confguration of the logging framework.
 * - xml.cpm.xlm\n
     Contains the XSEM mappings for known formats.
 * \section Administration
 * The Administration files are located in the 'opensearch/trunk/admin' direcotry.
 * The directory contains the following files:
 * - processqueue_init.sql\n
 *   SQL script used to initialize the Processqueue table and a stored procedure.
 * - statisticsDB_init.sql\n
 *   SQL script used to initialize the statisticsDB table.
 * - runall.sql\n
 *   Runs processqueue_init.sql and statisticsDB_init.sql
 * - query_processqueue.sql\n
 *   dumps the Processqueue.
 */
