/******************************************
 * THIS FILE HAS BEEN AUTOGENERATED USING *
 *                                        *
 *       create_test_suite_files.py       *
 ******************************************/

package dk.dbc.opensearch.common.os.tests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;


@RunWith(Suite.class)
@Suite.SuiteClasses(
    {
        FileFilterTest.class,
        XmlFileFilterTest.class,
        FileHandlerStaticCallTest.class,
        FileHandlerTest.class
    }
)
public class OSTestSuite 
{
    // Leave class empty!
}