/******************************************
 * THIS FILE HAS BEEN AUTOGENERATED USING *
 *                                        *
 *       create_test_suite_files.py       *
 ******************************************/

package dk.dbc.opensearch.components.datadock.tests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;


@RunWith(Suite.class)
@Suite.SuiteClasses(
    {
        DataDockPoolAdmTest.class,
        DataDockPoolTest.class,
        DataDockTest.class
    }
)
public class DATADOCKTestSuite 
{
    // Leave class empty!
}