
/******************************************
 * THIS FILE HAS BEEN AUTOGENERATED USING *
 *                                        *
 *       create_test_suite_files.py       *
 ******************************************/

package dk.dbc.opensearch.common.types.tests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;


@RunWith(Suite.class)
@Suite.SuiteClasses(
    {
        CargoMimeTypeTest.class,
        CargoObjectInfoTest.class,
        CargoContainerTest.class
    }
)
public class TYPESTestSuite 
{
    // Leave class empty!
}