/******************************************
 * THIS FILE HAS BEEN AUTOGENERATED USING *
 *                                        *
 *       create_test_suite_files.py       *
 ******************************************/

package dk.dbc.opensearch.components.pti.tests;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;


@RunWith(Suite.class)
@Suite.SuiteClasses(
    {
        PTIPoolTest.class,
        PTIPoolAdmTest.class,
        PTITest.class
    }
)
public class PTITestSuite 
{
    // Leave class empty!
}